#Generally designed with an idea of being cross compatible between compose and
#swarm mode.
version: '3.1'

services:
  #Our service.
  tweet_service:
    image: tweet_service
    container_name: tweet_service
    build:
      context: .
      dockerfile: ./tweet_service/Dockerfile
    restart: always
    ports:
      - ${tweet_service_port}:${tweet_service_port}
    depends_on:
      - tweet_db
    networks:
      - network
    

  tweet_db:
    image: postgres
    container_name: tweet_db
    restart: on-failure
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}

networks:
  network:
    driver: bridge