version: '3.8'

services:

  tweet_service:
    image: tweet_service
    container_name: tweet_service
    build:
      context: .
      dockerfile: ./tweet_service/Dockerfile
    restart: always
    ports:
      - ${TWEET_SERVICE_PORT}:${TWEET_SERVICE_PORT}
    environment:
      TWEET_DB_HOST: ${TWEET_DB_HOST}
      TWEET_DB_PORT: ${TWEET_DB_PORT}
      TWEET_SERVICE_PORT: ${TWEET_SERVICE_PORT}
    depends_on:
      - tweet_db
    networks:
      - network

  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    restart: always
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    environment:
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    depends_on:
      - user_db
    networks:
      - network

  auth_service:
    image: auth_service
    container_name: auth_service
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
    depends_on:
      - auth_db
    networks:
      - network

  tweet_db:
    image: mongo
    container_name: tweet_db
    restart: on-failure
    networks:
      - network

  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    networks:
      - network

  auth_db:
    image: mongo
    container_name: auth_db
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge